name: Run Scenarios
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'yarn'

      - name: Install packages
        run: yarn --non-interactive --frozen-lockfile

      - name: Run scenarios
        run: yarn simulate
